name: manage-azure-policy-29f6d87e
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Storage_Diag_to_Event_Hub_d11581e0-e750-4cea-9592-3b205f7d8ca5/**'
#      - .github/workflows/manage-azure-policy-29f6d87e.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_29f6d87e}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Storage_Diag_to_Event_Hub_d11581e0-e750-4cea-9592-3b205f7d8ca5/**
